### ISSUE TITLE
Incorrect License.md contact details

### ISSUE THREAD

**Issue by eyak** [arduino/arduino-create-agent#116]
The license file was copied without filling in actual contact details of SW creators.
It currently reads for example:
`{signature of Ty Coon}, 1 April 1989 Ty Coon, President of Vice`

**Comment by 00alis** [comment]
@mastrolinux

**Comment by mastrolinux** [comment]
Hi @eyak reading the licence completely it mentions:

```
You should also get your employer (if you work as a programmer) or your
school, if any, to sign a "copyright disclaimer" for the program, if
necessary.  Here is a **sample**; alter the names:
```

That means we have to add the proper header in every file (this is something we are going to do) but it is not related on the license itself because it is correct. So thank you for pointing this out but that file should not be changed. It is true we have to update other files.

**Comment by zmoog** [comment]
I created a new task in our internal tracking system to add a header in every `.go` file.

Closing this issue.
