### ISSUE TITLE
Unable to see ports for multiple boards

### ISSUE THREAD

**Issue by gguy1** [arduino/arduino-create-agent#152]
I don't see multiple ports when I connect multiple 101's to my machine.

I wanted to test using the BLE libraries one as central and another as peripheral. However I could not see both boards on my port list using the web editor.

- I am trying to do this in a chrome browser

- Ubuntu 16.04 OS

**Comment by 00alis** [comment]
Would you send us a screenshot of what you see in the board and ports dropdown as in the one below? Thanks.
<img width="286" alt="screenshot 2017-05-29 09 28 37" src="https://cloud.githubusercontent.com/assets/6151328/26540350/4dbef23c-4451-11e7-96dd-29f710bfdb36.png">

**Comment by facchinm** [comment]
Hi @gguy1 , one board is probably stuck in DFU mode (due to a bad update or some other reason). Simply attach one board at a time and flash them with a Blink. Once you make sure that both the boards expose the serial interface independently you can retest with both attached and they should both appear. If it doesn't happen, could you provide the debug output of your agent (right click on the tray, open debug console)? Thanks!

**Comment by gguy1** [comment]
I was able to see both of them trying the steps mentioned.
Thank You,
Gavin Guy

**Comment by facchinm** [comment]
Closing as solved
