### ISSUE TITLE
Limit Agent To Once Instance.

### ISSUE THREAD

**Issue by Vancer** [arduino/arduino-create-agent#217]
Hi Team,

Is there a way where I can run the `Arduino_Create_Bridge.exe` instance only once? 
Where I can block any other instance if the user executes the executable again.

Thank you.

**Comment by facchinm** [comment]
Hi @Vancer ,
the easiest way is to create a lockfile. Currently there is no such feature in the agent (because we need two instances running at the same time during installation).
However, if you want to propose a PR to implement this feature (configurable by .ini) I'll be glad to review and merge it.
