### ISSUE TITLE
device serial number returned only sometimes

### ISSUE THREAD

**Issue by smellai** [arduino/arduino-create-agent#265]
![image](https://user-images.githubusercontent.com/1763268/48188964-4a12f000-e33f-11e8-9f1d-5c1752d22795.png)

**Comment by smellai** [comment]
See https://github.com/arduino/arduino-create-agent/issues/231

**Comment by AlbyIanna** [comment]
As discussed with @cmaglie it appears that this behavior is due to the fact that some boards (mostly new boards) do not expose the serial number when they are in bootloader mode. If you quit the bootloader mode, for example uploading a sketch to the board or clicking the reset button just once, the serial number will be exposed again.
Closing this issue, because it doesn't concern the agent, and needs to be addressed in another way.
