### ISSUE TITLE
Port is persistently discovered after disconnect 

### ISSUE THREAD

**Issue by davegarthsimpson** [arduino/arduino-create-agent#808]
### Describe the problem

When using the agent, with the debug console, or web editors, often after a port is discovered, and visualised by the `list` command, it appears to persist indefinitely in the memory of the agent.

After the associated board is disconnected, it is continuously detected and continuously appears in response to the `list` command.

### To reproduce

1. Open the agent debug console
2. Connect a board via USB
3. Wait a few seconds
4. Run the `list` command
5. The port should appear in the response to the list command
6. Wait a few seconds
7. Disconnect the board
8. Wait a few seconds
9. Run the `list` command
10. The port continues to appear in the response to the list command (bug)

### Expected behavior

After the board is disconnected its port should no longer appear in the response to the list command.

### Arduino Create Agent version

1.3.2-d170a5e

### Operating system

macOS

### Operating system version

Ventura 13.1

### Browser

Chrome

### Browser version

115.0.5790.114

### Additional context

The problem is also visible with the web IDEs.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-create-agent/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by umbynos** [comment]
We could take advantage of this bug to introduce the [discovery protocol](https://arduino.github.io/arduino-cli/0.34/pluggable-discovery-specification/) in the agent. (some works has already been done in #773 

Advantages:
- The bug is fixed, since this is working in the CLI and IDE2
- We could remove some code duplication
- The agent is already able to install and run tools from the package_index
- In the future other discoveries can be added (like DFU one)

Disadvantages:
none
